# Generated by Django 5.2.6 on 2026-09-03 06:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Friday Night Live', max_length=160)),
                ('venue', models.CharField(default='The Grand Hall', max_length=160)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_key', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('hold', 'Hold'), ('booked', 'Booked'), ('expired', 'Expired')], default='hold', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.event')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=12)),
                ('row', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('available', 'Available'), ('held', 'Held'), ('booked', 'Booked')], default='available', max_length=12)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('current_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_seats', to='reservations.reservation')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='reservations.event')),
            ],
            options={
                'ordering': ['row', 'number'],
                'constraints': [models.UniqueConstraint(fields=('event', 'label'), name='unique_event_seat')],
            },
        ),
    ]
